package com.widescope.persistence;

public class PostgresSchema {


    /*
        CREATE TABLE IF NOT EXISTS executionScriptTable(id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
												scriptId BIGINT DEFAULT -1,
												requestId VARCHAR(65535),
												scriptName VARCHAR(65535),
												sourceMachine VARCHAR(65535),
												destinationMachine VARCHAR(65535),
												interpreterId BIGINT,
												grp VARCHAR(65535),
												src VARCHAR(1) DEFAULT 'A',
												userId BIGINT,
												scriptContent VARCHAR(65535),
												jsonParam VARCHAR(65535),
												repPath VARCHAR(65535),
												comment VARCHAR(65535),
												timestamp BIGINT);




        ALTER TABLE executionScriptTable ADD CONSTRAINT ck_executionScriptTable_3 CHECK (src IN ('A', 'R') );
        CREATE INDEX IF NOT EXISTS  idx_executionScriptTable_2 ON executionScriptTable(userId, timestamp);

        CREATE TABLE IF NOT EXISTS accessRefTable (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, executionId BIGINT, userId BIGINT);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_accessRefTable_1 ON accessRefTable(executionId, userId);
        ALTER TABLE accessRefTable ADD CONSTRAINT accessRefTableFk_1 FOREIGN KEY ( executionId ) REFERENCES executionScriptTable( id );
    * */
}
